import Aside from "@/components/Aside";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Movie DB Next App",
  description: "Generated by Sabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main>
          <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
          <Aside/>
          {children}
          </div>
        </main>
      </body>
    </html>
  );
}
